#!/bin/bash

if [ "$1" = "-h" ]; then
echo "As soon as I have time, there will be help"
fi

################################
# 1) Prepare variables
################################
APP_NAME=$1
APP_ROOT="/opt/bitnami/apps/$APP_NAME"
DOMAIN="${APP_NAME//-/.}"
DOMAIN_ALIAS="www.$DOMAIN"

################################
# 2) print app information
################################
printf "\n"
printf "App %s will be created.\n\n" "$APP_NAME"
printf "Directory: %s\n" "$APP_ROOT"
printf "Domain: %s\n" "$DOMAIN"
printf "Domain alias: %s\n" "$DOMAIN_ALIAS"
printf "\n"

################################
# 3) ask to confirm
################################
read -p "Proceed? [y/n] " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

################################
# 4) copy vhost folder
################################
cp -R "vhost/" $APP_ROOT

################################
# 5) copy SSL (for sandbox only)
################################
# cp "./star_sandbox_webvalley_cz.crt" "$CURRENT_APP_ROOT/ssl/star_sandbox_webvalley_cz.crt"
# cp "./star_sandbox_webvalley_cz.chain.crt" "$CURRENT_APP_ROOT/ssl/star_sandbox_webvalley_cz.chain.crt"
# cp "./star_sandbox_webvalley_cz.key" "$CURRENT_APP_ROOT/ssl/star_sandbox_webvalley_cz.key"
# cp "./star_sandbox_webvalleyagency_com.crt" "$CURRENT_APP_ROOT/ssl/star_sandbox_webvalleyagency_com.crt"
# cp "./star_sandbox_webvalleyagency_com.chain.crt" "$CURRENT_APP_ROOT/ssl/star_sandbox_webvalleyagency_com.chain.crt"
# cp "./star_sandbox_webvalleyagency_com.key" "$CURRENT_APP_ROOT/ssl/star_sandbox_webvalleyagency_com.key"

################################
# 6) copy placeholders
################################
find $APP_ROOT -type f -print0 | xargs -0 sed -i "s@%APP%@$APP_NAME@g"
find $APP_ROOT -type f -print0 | xargs -0 sed -i "s@%APP_ROOT%@$APP_ROOT@g"
find $APP_ROOT -type f -print0 | xargs -0 sed -i "s@%DOMAIN%@$DOMAIN@g"
find $APP_ROOT -type f -print0 | xargs -0 sed -i "s@%DOMAIN_ALIAS%@$DOMAIN_ALIAS@g"

################################
# 7) add necessary includes
################################
APACHE_VHOST_FILE="/opt/bitnami/apache2/conf/bitnami/bitnami-apps-vhosts.conf"
APACHE_APPEND_PHRASE="Include \"/opt/bitnami/apps/$APP_NAME/conf/httpd-vhosts.conf\""
grep -q -F "$APACHE_APPEND_PHRASE" $APACHE_VHOST_FILE || echo "$APACHE_APPEND_PHRASE" >> $APACHE_VHOST_FILE

PHP_CONFIG_FILE="/opt/bitnami/php/etc/php-fpm.conf"
PHP_APPEND_PHRASE="include=/opt/bitnami/apps/$APP_NAME/conf/php-fpm/pool.conf"
grep -q -F "$PHP_APPEND_PHRASE" $PHP_CONFIG_FILE || echo "$PHP_APPEND_PHRASE" >> $PHP_CONFIG_FILE

################################
# 8) fix file ownership
################################
chown bitnami:bitnami "$APP_ROOT/htdocs"
chown bitnami:daemon "$APP_ROOT/log"

printf "\n\n"
printf "App $APP_NAME has been created"
printf "\n"
printf "Execute /opt/bitnami/ctlscript.sh restart to apply the changes"
printf "\n"